const translations = {
  en: {
    navAbout: "About",
    navCapabilities: "R&D",
    navProjects: "Projects",
    navResearch: "Research",
    navContact: "Contact",
    heroEyebrow: "R&D / Engineering / Technology",
    heroTitle: "R&D partner for industrial technology solutions.",
    heroLead: "Research, design, special materials, and field engineering support for practical enterprise projects.",
    downloadKicker: "Download",
    downloadKicker2: "Download",
    downloadProfile: "Company Profile",
    viewProjects: "View Project Work",
    aboutEyebrow: "Company profile",
    aboutTitle: "Experienced team for practical engineering work.",
    aboutBody1: "Established on October 3, 2011, Hiflowsolution Co., Ltd. focuses on R&D, design, special materials, inspection, control systems, network infrastructure, and project implementation.",
    aboutBody2: "The company works with practical engineering problems, including network infrastructure, CCTV maintenance, electrical inspection, control systems, and research-oriented technology development.",
    factLegal: "Legal entity",
    factReg: "Registration no.",
    factTeam: "Core team",
    factTeamValue: "Managed by electrical engineering and IT professionals",
    factArea: "Service area",
    capEyebrow: "Technology capabilities",
    capTitle: "From research concept to field service.",
    cap1Title: "R&D and Design",
    cap1Body: "Applied research, engineering design, prototype support, and special material sourcing.",
    cap2Title: "Control and Robotics",
    cap2Body: "DC motor control, phenotyping robot concepts, simulation, and precision motion-control support.",
    cap3Title: "Infrastructure and Security",
    cap3Body: "Cisco network, LAN/WAN, wireless, firewall, CCTV, and site maintenance support.",
    cap4Title: "Inspection and Maintenance",
    cap4Body: "Electrical inspection, thermal imaging, preventive maintenance, and implementation.",
    projectsEyebrow: "Selected work",
    projectsTitle: "Selected field work.",
    gallery1: "Thermal imaging for electrical inspection",
    gallery2: "Electrical measurement and field testing",
    gallery3: "CCTV field maintenance and service coordination",
    gallery4: "CCTV monitoring and verification",
    gallery5: "Control cabinet inspection and maintenance",
    customerRefs: "Customer references: Kasetsart University, PTT, and STE. Detailed project references are confidential.",
    researchEyebrow: "Research references",
    researchTitle: "Research references",
    researchDownloadNote: "Downloadable academic papers and prototype references supporting the R&D profile.",
    paper1Title: "Automated AMBU ventilator and negative pressure capsule",
    paper2Title: "FITSMC for phenotyping robot servo motor systems",
    openPaper: "Open paper",
    openPaper2: "Open paper",
    contactEyebrow: "Contact",
    contactIntro: "For R&D collaboration, vendor review, procurement, or project coordination, please contact the company representative below.",
    contactPerson: "Contact person",
    phone: "Phone",
    address: "Address",
    registeredAddress: "Registered address",
    footerText: "R&D, engineering design, and applied technology services."
  },
  th: {
    navAbout: "เกี่ยวกับบริษัท",
    navCapabilities: "ความสามารถ",
    navProjects: "ผลงาน",
    navResearch: "งานวิจัย",
    navContact: "ติดต่อ",
    heroEyebrow: "R&D / วิศวกรรม / เทคโนโลยี",
    heroTitle: "พันธมิตร R&D สำหรับโซลูชันเทคโนโลยีอุตสาหกรรม",
    heroLead: "งานวิจัย ออกแบบ วัสดุพิเศษ และวิศวกรรมภาคสนามสำหรับโครงการองค์กรที่ใช้งานได้จริง",
    downloadKicker: "Download",
    downloadKicker2: "Download",
    downloadProfile: "Company Profile",
    viewProjects: "ดูผลงาน",
    aboutEyebrow: "ข้อมูลบริษัท",
    aboutTitle: "ทีมงานมากประสบการณ์",
    aboutBody1: "ก่อตั้งเมื่อวันที่ 3 ตุลาคม 2554 Hiflowsolution Co., Ltd. มุ่งเน้น R&D, design, วัสดุพิเศษ, inspection, control systems, network infrastructure และ project implementation",
    aboutBody2: "บริษัททำงานกับโจทย์วิศวกรรมเชิงปฏิบัติ เช่น network infrastructure, งานบำรุงรักษา CCTV, งานตรวจระบบไฟฟ้า, control systems และงานพัฒนาเทคโนโลยีเชิงวิจัย",
    factLegal: "ชื่อนิติบุคคล",
    factReg: "เลขทะเบียนบริษัท",
    factTeam: "ทีมหลัก",
    factTeamValue: "ทีมงานบริหารงานโดยทีมวิศวกรไฟฟ้าและ IT",
    factArea: "พื้นที่ให้บริการ",
    capEyebrow: "ความสามารถด้านเทคโนโลยี",
    capTitle: "ตั้งแต่แนวคิดวิจัยจนถึงบริการหน้างาน",
    cap1Title: "R&D และ Design",
    cap1Body: "งานวิจัยประยุกต์ ออกแบบวิศวกรรม prototype และจัดหาวัสดุพิเศษ",
    cap2Title: "Control และ Robotics",
    cap2Body: "DC motor control, phenotyping robot, simulation และ precision motion control",
    cap3Title: "Infrastructure และ Security",
    cap3Body: "Cisco network, LAN/WAN, wireless, firewall, CCTV และงานดูแลระบบ",
    cap4Title: "Inspection และ Maintenance",
    cap4Body: "ตรวจระบบไฟฟ้า thermal imaging, preventive maintenance และ implementation",
    projectsEyebrow: "ผลงานที่คัดเลือก",
    projectsTitle: "ผลงานภาคสนามที่คัดเลือก",
    gallery1: "งานตรวจระบบไฟฟ้าด้วย thermal imaging",
    gallery2: "งานวัดและทดสอบระบบไฟฟ้าภาคสนาม",
    gallery3: "งานบำรุงรักษา CCTV และประสานงานหน้างาน",
    gallery4: "งานตรวจสอบระบบ CCTV monitoring",
    gallery5: "งานตรวจและบำรุงรักษาตู้ควบคุม",
    customerRefs: "ลูกค้าอ้างอิง: Kasetsart University, PTT และ STE รายละเอียดโครงการอยู่ภายใต้การรักษาความลับของลูกค้า",
    researchEyebrow: "งานวิจัยอ้างอิง",
    researchTitle: "งานวิจัยอ้างอิง",
    researchDownloadNote: "ดาวน์โหลด paper และเอกสาร prototype ที่สนับสนุนภาพลักษณ์ด้าน R&D",
    paper1Title: "Automated AMBU ventilator และ negative pressure capsule",
    paper2Title: "FITSMC สำหรับ servo motor ใน phenotyping robot",
    openPaper: "เปิด paper",
    openPaper2: "เปิด paper",
    contactEyebrow: "ติดต่อ",
    contactIntro: "สำหรับงาน R&D, vendor review, procurement หรือ project coordination กรุณาติดต่อผู้ประสานงานบริษัทด้านล่าง",
    contactPerson: "ผู้ติดต่อ",
    phone: "เบอร์โทร",
    address: "ที่อยู่",
    registeredAddress: "ที่อยู่จดทะเบียน",
    footerText: "บริการ R&D, engineering design และ applied technology"
  },
  ja: {
    navAbout: "会社概要",
    navCapabilities: "技術領域",
    navProjects: "実績",
    navResearch: "研究",
    navContact: "連絡先",
    heroEyebrow: "R&D / エンジニアリング / 技術",
    heroTitle: "産業技術ソリューションのためのR&Dパートナー",
    heroLead: "研究、設計、特殊材料、現場エンジニアリングで実用的な企業プロジェクトを支援します。",
    downloadKicker: "Download",
    downloadKicker2: "Download",
    downloadProfile: "Company Profile",
    viewProjects: "実績を見る",
    aboutEyebrow: "会社概要",
    aboutTitle: "実務経験豊富なチームです。",
    aboutBody1: "2011年10月3日設立。R&D、設計、特殊材料、検査、制御、ネットワーク、プロジェクト実行に対応します。",
    aboutBody2: "ネットワークインフラ、CCTV保守、電気検査、制御システム、研究開発型の技術開発など、実践的なエンジニアリング課題に取り組みます。",
    factLegal: "法人名",
    factReg: "会社登録番号",
    factTeam: "主要チーム",
    factTeamValue: "電気エンジニアとITプロフェッショナルが運営",
    factArea: "対応地域",
    capEyebrow: "技術対応領域",
    capTitle: "研究コンセプトから現場サービスまで",
    cap1Title: "R&Dと設計",
    cap1Body: "応用研究、設計、試作支援、特殊材料調達を支援します。",
    cap2Title: "制御とロボティクス",
    cap2Body: "DCモータ制御、フェノタイピングロボット、シミュレーション、精密制御を支援します。",
    cap3Title: "インフラとセキュリティ",
    cap3Body: "Ciscoネットワーク、LAN/WAN、無線、ファイアウォール、CCTV、保守を支援します。",
    cap4Title: "検査と保守",
    cap4Body: "電気検査、サーモグラフィ、予防保全、実装を行います。",
    projectsEyebrow: "主な実績",
    projectsTitle: "主な現場実績",
    gallery1: "サーモグラフィによる電気検査",
    gallery2: "現場での電気測定と試験",
    gallery3: "CCTV現場保守とサービス調整",
    gallery4: "CCTV監視システムの確認",
    gallery5: "制御盤の点検と保守",
    customerRefs: "参考顧客: Kasetsart University、PTT、STE。詳細なプロジェクト情報は顧客機密として扱います。",
    researchEyebrow: "研究参考資料",
    researchTitle: "研究参考資料",
    researchDownloadNote: "R&Dプロフィールを支える論文とプロトタイプ資料をダウンロードできます。",
    paper1Title: "Automated AMBU ventilator and negative pressure capsule",
    paper2Title: "FITSMC for phenotyping robot servo motor systems",
    openPaper: "論文を開く",
    openPaper2: "論文を開く",
    contactEyebrow: "連絡先",
    contactIntro: "R&D協業、ベンダー審査、調達、プロジェクト調整については、下記担当者までご連絡ください。",
    contactPerson: "担当者",
    phone: "電話",
    address: "住所",
    registeredAddress: "登記住所",
    footerText: "R&D、エンジニアリング設計、応用技術サービス"
  }
};

function setLanguage(lang) {
  const dictionary = translations[lang] || translations.en;
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.getAttribute("data-i18n");
    if (dictionary[key]) {
      node.textContent = dictionary[key];
    }
  });
  document.querySelectorAll(".language-switcher button").forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === lang);
  });
  localStorage.setItem("hiflow-language", lang);
}

document.querySelectorAll(".language-switcher button").forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});

setLanguage(localStorage.getItem("hiflow-language") || "en");
